### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 12people** [Alamantus/insanity-word-list#2]
What license can these words be used under?

**Comment by Alamantus** [comment]
I am so sorry I never replied to this—I had no idea this issue even got created here! I just applied the [Unlicense](https://unlicense.org) to the repository, and I will update the NPM package with it as soon as I am able.

**Comment by 12people** [comment]
@Alamantus Thanks for taking a look at this!

The Unlicense specifically covers software — see its wording:

> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <http://unlicense.org/>

As such, I'm afraid the word sets might not be covered under this license, simply because they arguably don't constitute software.

Could they be published under a similar license, such as [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)?

**Comment by Alamantus** [comment]
Shoot, you're probably right—I haven't looked at this repo in so long I couldn't remember if I actually had any JS written with it. The intent was to put it into public domain, which I believe CC0 does, so I will change it to that!

**Comment by 12people** [comment]
Awesome, thanks!
